// Run with:
// DATABASE_URL="postgresql://postgres:fnQlbZXsbAxbsZpIxGlKfPUvnbRPLpxX@kodama.proxy.rlwy.net:45003/railway" node seed-deals.js

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const ORG_ID = 'a296974d-74f4-4c8b-b6f4-5a57b9f36758';

const deals = [
  {
    address: '1518 Dallas St',
    city: 'Killeen',
    state: 'TX',
    zipCode: '76541',
    county: 'Bell County',
    propertyType: 'SINGLE_FAMILY',
    beds: 3,
    baths: 2,
    sqft: 1340,
    yearBuilt: 2001,
    askingPrice: 89000,
    arv: 165000,
    repairEstimate: 28000,
    spread: 48000,
    seventyPercentRuleMax: 87500,
    rentEstimate: 1350,
    overallCondition: 'MEDIUM_REHAB',
    occupancy: 'VACANT',
    accessInfo: 'Lockbox',
    sourceType: 'JV',
    sourceName: 'Marcus Realty Group',
    sourcePhone: '+12545550101',
    dealType: 'WHOLESALE',
    vacantAtClose: 'YES',
    financingAllowed: 'CASH_ONLY',
    description: 'Solid 3/2 in Killeen near Ft Cavazos. Medium rehab needed — kitchen and baths dated, roof 8 years old. Strong rental demand in this zip. Cash only.',
    status: 'READY_TO_MATCH',
    dealPriorityScore: 72,
    dataCompletenessScore: 78,
    missingInfoCount: 3,
    missingInfo: ['Photos', 'Closing date', 'Foundation condition'],
    nextBestAction: 'Generate follow-up message',
    marketKey: 'Killeen, TX',
    buyerCoverageStatus: 'Buyer Gap',
    buyerGapScore: 68,
    marketBuyerNeedRecommendation: 'Find more Killeen/Temple cash buyers — landlords and buy-and-hold investors near Ft Cavazos',
  },
  {
    address: '129 73rd St N',
    city: 'Birmingham',
    state: 'AL',
    zipCode: '35206',
    county: 'Jefferson County',
    propertyType: 'SINGLE_FAMILY',
    beds: 3,
    baths: 1,
    sqft: 1180,
    yearBuilt: 1968,
    askingPrice: 52000,
    arv: 118000,
    repairEstimate: 35000,
    spread: 31000,
    seventyPercentRuleMax: 47600,
    rentEstimate: 1100,
    overallCondition: 'HEAVY_REHAB',
    occupancy: 'VACANT',
    accessInfo: 'Lockbox',
    sourceType: 'FACEBOOK',
    sourceName: 'Darnell Wholesale',
    sourcePhone: '+12055550198',
    facebookGroupName: 'Birmingham Wholesale Deals',
    dealType: 'WHOLESALE',
    vacantAtClose: 'YES',
    financingAllowed: 'CASH_ONLY',
    description: 'Heavy rehab 3/1 in Birmingham 35206. Needs full kitchen, bathrooms, flooring, and HVAC. Strong ARV in this zip — good flip or rental hold. Vacant, lockbox available.',
    status: 'READY_TO_MATCH',
    dealPriorityScore: 65,
    dataCompletenessScore: 72,
    missingInfoCount: 4,
    missingInfo: ['Photos', 'Closing date', 'Roof age', 'Foundation condition'],
    nextBestAction: 'Generate follow-up message',
    marketKey: 'Birmingham, AL',
    buyerCoverageStatus: 'Weak Coverage',
    buyerGapScore: 58,
    marketBuyerNeedRecommendation: 'Find more Birmingham cash buyers — Section 8 landlords and heavy-rehab flippers needed in 35206',
  },
  {
    address: '1735 Silver St',
    city: 'Jacksonville',
    state: 'FL',
    zipCode: '32206',
    county: 'Duval County',
    propertyType: 'SINGLE_FAMILY',
    beds: 3,
    baths: 2,
    sqft: 1420,
    yearBuilt: 1955,
    askingPrice: 95000,
    arv: 185000,
    repairEstimate: 42000,
    spread: 48000,
    seventyPercentRuleMax: 87500,
    rentEstimate: 1650,
    overallCondition: 'MEDIUM_REHAB',
    occupancy: 'VACANT',
    accessInfo: 'Lockbox',
    sourceType: 'OWN',
    sourceName: 'BigBuck Offers',
    dealType: 'WHOLESALE',
    vacantAtClose: 'YES',
    financingAllowed: 'HARD_MONEY_OK',
    zillowUrl: 'https://www.zillow.com/homes/1735-Silver-St-Jacksonville-FL/',
    description: 'Historic district 3/2 in Jacksonville 32206. Classic block construction, needs kitchen and bath update, roof 12 years. Excellent comps in this zip. Hard money OK.',
    status: 'READY_TO_BLAST',
    dealPriorityScore: 84,
    dataCompletenessScore: 88,
    missingInfoCount: 1,
    missingInfo: ['Photos'],
    nextBestAction: 'Generate buyer blast',
    matchedBuyerCount: 12,
    tier1MatchCount: 3,
    buyerDemandScore: 60,
    marketKey: 'Jacksonville, FL',
    buyerCoverageStatus: 'Moderate Coverage',
    buyerGapScore: 24,
    marketBuyerNeedRecommendation: '',
  },
  {
    address: '3904 Arrejo Ct',
    city: 'Belle Isle',
    state: 'FL',
    zipCode: '32812',
    county: 'Orange County',
    propertyType: 'SINGLE_FAMILY',
    beds: 4,
    baths: 2,
    sqft: 1890,
    yearBuilt: 1978,
    askingPrice: 235000,
    arv: 385000,
    repairEstimate: 55000,
    spread: 95000,
    seventyPercentRuleMax: 214500,
    rentEstimate: 2400,
    overallCondition: 'MEDIUM_REHAB',
    occupancy: 'VACANT',
    accessInfo: 'By Appointment',
    sourceType: 'JV',
    sourceName: 'Central FL Investments',
    sourcePhone: '+14075550312',
    jvSplit: '50/50',
    jvAgreementStatus: 'Verbal',
    dealType: 'WHOLESALE',
    vacantAtClose: 'YES',
    financingAllowed: 'HARD_MONEY_OK',
    description: 'Large 4/2 in Belle Isle — one of Central Florida\'s most desirable suburbs. Big spread, strong comps. Medium rehab — kitchen, baths, flooring. JV deal, 50/50 split available.',
    status: 'READY_TO_MATCH',
    dealPriorityScore: 91,
    dataCompletenessScore: 82,
    missingInfoCount: 2,
    missingInfo: ['Photos', 'Roof age'],
    nextBestAction: 'Run buyer match',
    matchedBuyerCount: 8,
    tier1MatchCount: 2,
    buyerDemandScore: 40,
    marketKey: 'Belle Isle, FL',
    buyerCoverageStatus: 'Moderate Coverage',
    buyerGapScore: 51,
    marketBuyerNeedRecommendation: 'Find more Central Florida buyers for 4+ bed homes — this is a premium market with strong comps',
  },
  {
    address: '1983 Hillcrest Cir',
    city: 'Gordonville',
    state: 'TX',
    zipCode: '76245',
    county: 'Grayson County',
    propertyType: 'SINGLE_FAMILY',
    beds: 3,
    baths: 2,
    sqft: 1737,
    yearBuilt: 2019,
    askingPrice: 32000,
    arv: 0,
    repairEstimate: 0,
    spread: 0,
    seventyPercentRuleMax: 0,
    rentEstimate: 1850,
    currentRent: 1850,
    overallCondition: 'TURNKEY',
    occupancy: 'TENANT_OCCUPIED',
    accessInfo: 'Tenant Access',
    sourceType: 'OWN',
    sourceName: 'BigBuck Offers',
    dealType: 'SUBTO',
    vacantAtClose: 'NO',
    financingAllowed: 'UNKNOWN',
    description: 'Subject-To deal — 2019 build, tenant paying $1,850/mo, PITI $1,471. HomeTap equity position on title. Entry ~$32k. 2.8% interest rate assumable. Strong cash flow day 1.',
    status: 'READY_TO_BLAST',
    dealPriorityScore: 88,
    dataCompletenessScore: 91,
    missingInfoCount: 1,
    missingInfo: ['ARV (not applicable for Subto)'],
    nextBestAction: 'Generate buyer blast',
    matchedBuyerCount: 18,
    tier1MatchCount: 5,
    buyerDemandScore: 90,
    marketKey: 'Gordonville, TX',
    buyerCoverageStatus: 'Strong Coverage',
    buyerGapScore: 0,
    marketBuyerNeedRecommendation: '',
  },
];

async function main() {
  console.log('🌱 Seeding deals...');

  for (const deal of deals) {
    const created = await prisma.deal.create({
      data: {
        organizationId: ORG_ID,
        ...deal,
        otherDocumentUrls: [],
        missingInfo: deal.missingInfo || [],
        photos: [],
        videos: [],
      },
    });
    console.log(`✅ Created: ${created.address}, ${created.city} — Priority Score: ${created.dealPriorityScore}`);
  }

  console.log('\n🎉 Done! 5 deals seeded.');
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
