-- DispoAI Deal Model Expansion Migration
-- Run after: npx prisma migrate dev --name "expand_deal_fields"

-- Source/JV fields
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "sourceType" TEXT DEFAULT 'MANUAL';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "dealType" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "rawInputText" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "originalPostText" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "sourceName" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "sourcePhone" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "sourceEmail" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "sourceCompany" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "facebookProfileUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "facebookPostUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "facebookGroupName" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "jvSplit" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "jvAgreementStatus" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "sourceNotes" TEXT;

-- Property fields
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "county" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "lotSize" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "yearBuilt" INTEGER;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "occupancy" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "accessInfo" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "hoaStatus" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "floodZone" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "description" TEXT;

-- Financial fields
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "buyerFacingPrice" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "internalContractPrice" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "assignmentFee" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "jvFee" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "rentEstimate" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "currentRent" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "taxesAnnual" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "insuranceEstimate" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "hoaMonthly" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "spread" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "seventyPercentRuleMax" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "pricePerSqft" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "arvPerSqft" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "rentToPriceRatio" DOUBLE PRECISION;

-- Condition fields
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "overallCondition" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "roofCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "roofAge" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "hvacCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "hvacAge" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "foundationCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "plumbingCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "electricalCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "kitchenCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "bathroomCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "flooringCondition" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "moldOrWaterDamage" BOOLEAN DEFAULT false;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "fireDamage" BOOLEAN DEFAULT false;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "codeIssues" BOOLEAN DEFAULT false;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "conditionNotes" TEXT;

-- Timeline fields
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "contractDate" TIMESTAMP;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "inspectionDeadline" TIMESTAMP;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "emdDueDate" TIMESTAMP;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "closingDate" TIMESTAMP;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "assignmentDeadline" TIMESTAMP;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "titleCompany" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "escrowOfficer" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "assignmentAllowed" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "doubleCloseNeeded" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "financingAllowed" TEXT DEFAULT 'UNKNOWN';
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "vacantAtClose" TEXT DEFAULT 'UNKNOWN';

-- Links/media
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "redfinUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "redfinEstimate" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "googleMapsUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "streetViewUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "photosUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "inspectionReportUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "repairQuoteUrl" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "otherDocumentUrls" TEXT[];

-- AI / scoring fields
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "aiSummary" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "buyerFacingSummary" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "internalSummary" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "aiDealMathSummary" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "missingInfo" TEXT[];
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "aiFollowUpQuestions" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "dealPriorityScore" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "buyerDemandScore" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "dataCompletenessScore" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "missingInfoCount" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "matchedBuyerCount" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "tier1MatchCount" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "nextBestAction" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "buyerCoverageStatus" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "buyerGapScore" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "marketKey" TEXT;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "marketDemandScore" INTEGER DEFAULT 0;
ALTER TABLE "Deal" ADD COLUMN IF NOT EXISTS "marketBuyerNeedRecommendation" TEXT;
