-- AlterTable
ALTER TABLE "deals" ADD COLUMN     "accessInfo" TEXT,
ADD COLUMN     "aiDealMathSummary" TEXT,
ADD COLUMN     "aiFollowUpQuestions" TEXT,
ADD COLUMN     "aiSummary" TEXT,
ADD COLUMN     "arvPerSqft" DOUBLE PRECISION,
ADD COLUMN     "assignmentAllowed" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "assignmentDeadline" TIMESTAMP(3),
ADD COLUMN     "bathroomCondition" TEXT,
ADD COLUMN     "buyerCoverageStatus" TEXT,
ADD COLUMN     "buyerDemandScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "buyerFacingPrice" DOUBLE PRECISION,
ADD COLUMN     "buyerFacingSummary" TEXT,
ADD COLUMN     "buyerGapScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "closingDate" TIMESTAMP(3),
ADD COLUMN     "codeIssues" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "conditionNotes" TEXT,
ADD COLUMN     "contractDate" TIMESTAMP(3),
ADD COLUMN     "currentRent" DOUBLE PRECISION,
ADD COLUMN     "dataCompletenessScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dealPriorityScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "dealType" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "doubleCloseNeeded" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "electricalCondition" TEXT,
ADD COLUMN     "emdDueDate" TIMESTAMP(3),
ADD COLUMN     "escrowOfficer" TEXT,
ADD COLUMN     "facebookGroupName" TEXT,
ADD COLUMN     "facebookPostUrl" TEXT,
ADD COLUMN     "facebookProfileUrl" TEXT,
ADD COLUMN     "financingAllowed" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "fireDamage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "floodZone" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "flooringCondition" TEXT,
ADD COLUMN     "foundationCondition" TEXT,
ADD COLUMN     "googleDriveUrl" TEXT,
ADD COLUMN     "googleMapsUrl" TEXT,
ADD COLUMN     "hoaMonthly" DOUBLE PRECISION,
ADD COLUMN     "hoaStatus" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "hvacAge" TEXT,
ADD COLUMN     "hvacCondition" TEXT,
ADD COLUMN     "inspectionDeadline" TIMESTAMP(3),
ADD COLUMN     "inspectionReportUrl" TEXT,
ADD COLUMN     "insuranceEstimate" DOUBLE PRECISION,
ADD COLUMN     "internalContractPrice" DOUBLE PRECISION,
ADD COLUMN     "internalSummary" TEXT,
ADD COLUMN     "jvAgreementStatus" TEXT,
ADD COLUMN     "jvFee" DOUBLE PRECISION,
ADD COLUMN     "jvSplit" TEXT,
ADD COLUMN     "kitchenCondition" TEXT,
ADD COLUMN     "marketBuyerNeedRecommendation" TEXT,
ADD COLUMN     "marketDemandScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "marketKey" TEXT,
ADD COLUMN     "matchedBuyerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "missingInfo" TEXT[],
ADD COLUMN     "missingInfoCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "moldOrWaterDamage" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "nextBestAction" TEXT,
ADD COLUMN     "originalPostText" TEXT,
ADD COLUMN     "otherDocumentUrls" TEXT[],
ADD COLUMN     "overallCondition" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "photosUrl" TEXT,
ADD COLUMN     "plumbingCondition" TEXT,
ADD COLUMN     "pricePerSqft" DOUBLE PRECISION,
ADD COLUMN     "rawInputText" TEXT,
ADD COLUMN     "realtorEstimate" DOUBLE PRECISION,
ADD COLUMN     "realtorUrl" TEXT,
ADD COLUMN     "redfinEstimate" DOUBLE PRECISION,
ADD COLUMN     "redfinUrl" TEXT,
ADD COLUMN     "rentEstimate" DOUBLE PRECISION,
ADD COLUMN     "rentToPriceRatio" DOUBLE PRECISION,
ADD COLUMN     "repairQuoteUrl" TEXT,
ADD COLUMN     "roofAge" TEXT,
ADD COLUMN     "roofCondition" TEXT,
ADD COLUMN     "seventyPercentRuleMax" DOUBLE PRECISION,
ADD COLUMN     "sourceCompany" TEXT,
ADD COLUMN     "sourceEmail" TEXT,
ADD COLUMN     "sourceName" TEXT,
ADD COLUMN     "sourceNotes" TEXT,
ADD COLUMN     "sourcePhone" TEXT,
ADD COLUMN     "sourceType" TEXT DEFAULT 'MANUAL',
ADD COLUMN     "spread" DOUBLE PRECISION,
ADD COLUMN     "streetViewUrl" TEXT,
ADD COLUMN     "taxesAnnual" DOUBLE PRECISION,
ADD COLUMN     "tier1MatchCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "titleCompany" TEXT,
ADD COLUMN     "vacantAtClose" TEXT DEFAULT 'UNKNOWN',
ADD COLUMN     "zillowEstimate" DOUBLE PRECISION,
ADD COLUMN     "zillowUrl" TEXT;
